<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cursor Logo_cropper-point</name>
   <tag></tag>
   <elementGuidId>213eac23-026d-4afe-bec1-14eccca3308d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.cropper-point.point-nw</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cropper-model']/div/div/div[2]/div/div[3]/span[15]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cropper-point point-nw</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cropper-action</name>
      <type>Main</type>
      <value>nw</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cropper-model&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;crop-logo-container&quot;]/div[@class=&quot;cropper-container cropper-bg&quot;]/div[@class=&quot;cropper-crop-box&quot;]/span[@class=&quot;cropper-point point-nw&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cropper-model']/div/div/div[2]/div/div[3]/span[15]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[15]</value>
   </webElementXpaths>
</WebElementEntity>
